#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# Path to the current BSP
SEARCH_TARGET_CYPM1311=bsps/TARGET_CYPM1311

# The search paths for the included middleware
SEARCH_pdstack=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/pdstack/release-v4.0.0
SEARCH_pdutils=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/pdutils/release-v1.30.0
SEARCH_pmg-app-common=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/pmg-app-common/release-v2.0.0
SEARCH_cmsis=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/cmsis/release-v5.8.2
SEARCH_core-lib=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/core-lib/release-v1.6.0
SEARCH_core-make=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/core-make/release-v3.8.0
SEARCH_mtb-pdl-cat2=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/mtb-pdl-cat2/release-v2.19.1
SEARCH_recipe-make-cat2=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/recipe-make-cat2/release-v2.5.0

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_pdstack)
SEARCH_MTB_MK+=$(SEARCH_pdutils)
SEARCH_MTB_MK+=$(SEARCH_pmg-app-common)
SEARCH_MTB_MK+=$(SEARCH_cmsis)
SEARCH_MTB_MK+=$(SEARCH_core-lib)
SEARCH_MTB_MK+=$(SEARCH_core-make)
SEARCH_MTB_MK+=$(SEARCH_mtb-pdl-cat2)
SEARCH_MTB_MK+=$(SEARCH_recipe-make-cat2)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_PDSTACK
COMPONENTS += MW_PDUTILS
COMPONENTS += MW_PMG_APP_COMMON
COMPONENTS += MW_CMSIS
COMPONENTS += MW_CORE_LIB
COMPONENTS += MW_CORE_MAKE
COMPONENTS += MW_MTB_PDL_CAT2
COMPONENTS += MW_RECIPE_MAKE_CAT2

# Register map file
DEVICE_CYPM1311-48LQXI_SVD=$(SEARCH_mtb-pdl-cat2)/devices/svd/pmg1s3.svd


#
# generate make targets for the graphical editors that are specific to this project
#

modlibs:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: modlibs

CY_HELP_modlibs=Launches the Library Manager 2.60 GUI
CY_HELP_modlibs_VERBOSE=Launches the Library Manager 2.60 GUI. Check the Library Manager 2.60 User Guide for more information.
mtb_help_tool_modlibs:
	@:
	$(info $(MTB__SPACE)modlibs             $(CY_HELP_modlibs))

mtb_help_tools_end: mtb_help_tool_modlibs
mtb_help_tool_modlibs: mtb_help_tools_start
.PHONY: mtb_help_tool_modlibs

library-manager:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: library-manager

CY_HELP_library-manager=Launches the Library Manager 2.60 GUI
CY_HELP_library-manager_VERBOSE=Launches the Library Manager 2.60 GUI. Check the Library Manager 2.60 User Guide for more information.
mtb_help_tool_library-manager:
	@:
	$(info $(MTB__SPACE)library-manager     $(CY_HELP_library-manager))

mtb_help_tools_end: mtb_help_tool_library-manager
mtb_help_tool_library-manager: mtb_help_tools_start
.PHONY: mtb_help_tool_library-manager

config:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: config

CY_HELP_config=Launches the Device Configurator 5.60 GUI for the target's modus file
CY_HELP_config_VERBOSE=Launches the Device Configurator 5.60 GUI. Check the Device Configurator 5.60 User Guide for more information.
mtb_help_tool_config:
	@:
	$(info $(MTB__SPACE)config              $(CY_HELP_config))

mtb_help_tools_end: mtb_help_tool_config
mtb_help_tool_config: mtb_help_tools_start
.PHONY: mtb_help_tool_config

device-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: device-configurator

CY_HELP_device-configurator=Launches the Device Configurator 5.60 GUI for the target's modus file
CY_HELP_device-configurator_VERBOSE=Launches the Device Configurator 5.60 GUI. Check the Device Configurator 5.60 User Guide for more information.
mtb_help_tool_device-configurator:
	@:
	$(info $(MTB__SPACE)device-configurator $(CY_HELP_device-configurator))

mtb_help_tools_end: mtb_help_tool_device-configurator
mtb_help_tool_device-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_device-configurator

bsp-assistant:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bsp-assistant
.PHONY: bsp-assistant

CY_HELP_bsp-assistant=Launches the BSP Assistant 1.60 GUI
CY_HELP_bsp-assistant_VERBOSE=Launches the BSP Assistant 1.60 GUI. Check the BSP Assistant 1.60 User Guide for more information.
mtb_help_tool_bsp-assistant:
	@:
	$(info $(MTB__SPACE)bsp-assistant       $(CY_HELP_bsp-assistant))

mtb_help_tools_end: mtb_help_tool_bsp-assistant
mtb_help_tool_bsp-assistant: mtb_help_tools_start
.PHONY: mtb_help_tool_bsp-assistant

config_usbdev:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name usbdev-configurator
.PHONY: config_usbdev

CY_HELP_config_usbdev=Launches the USB Configurator [for USBDEV middleware] 3.10 GUI for the target's cyusbdev file
CY_HELP_config_usbdev_VERBOSE=Launches the USB Configurator [for USBDEV middleware] 3.10 GUI. Check the USB Configurator [for USBDEV middleware] 3.10 User Guide for more information.
mtb_help_tool_config_usbdev:
	@:
	$(info $(MTB__SPACE)config_usbdev       $(CY_HELP_config_usbdev))

mtb_help_tools_end: mtb_help_tool_config_usbdev
mtb_help_tool_config_usbdev: mtb_help_tools_start
.PHONY: mtb_help_tool_config_usbdev

usbdev-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name usbdev-configurator
.PHONY: usbdev-configurator

CY_HELP_usbdev-configurator=Launches the USB Configurator [for USBDEV middleware] 3.10 GUI for the target's cyusbdev file
CY_HELP_usbdev-configurator_VERBOSE=Launches the USB Configurator [for USBDEV middleware] 3.10 GUI. Check the USB Configurator [for USBDEV middleware] 3.10 User Guide for more information.
mtb_help_tool_usbdev-configurator:
	@:
	$(info $(MTB__SPACE)usbdev-configurator $(CY_HELP_usbdev-configurator))

mtb_help_tools_end: mtb_help_tool_usbdev-configurator
mtb_help_tool_usbdev-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_usbdev-configurator

config_ezpd:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name ez-pd-configurator
.PHONY: config_ezpd

CY_HELP_config_ezpd=Launches the EZ-PD™ Configurator 2.30 GUI for the target's mtbezpd file
CY_HELP_config_ezpd_VERBOSE=Launches the EZ-PD™ Configurator 2.30 GUI. Check the EZ-PD™ Configurator 2.30 User Guide for more information.
mtb_help_tool_config_ezpd:
	@:
	$(info $(MTB__SPACE)config_ezpd         $(CY_HELP_config_ezpd))

mtb_help_tools_end: mtb_help_tool_config_ezpd
mtb_help_tool_config_ezpd: mtb_help_tools_start
.PHONY: mtb_help_tool_config_ezpd

ez-pd-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name ez-pd-configurator
.PHONY: ez-pd-configurator

CY_HELP_ez-pd-configurator=Launches the EZ-PD™ Configurator 2.30 GUI for the target's mtbezpd file
CY_HELP_ez-pd-configurator_VERBOSE=Launches the EZ-PD™ Configurator 2.30 GUI. Check the EZ-PD™ Configurator 2.30 User Guide for more information.
mtb_help_tool_ez-pd-configurator:
	@:
	$(info $(MTB__SPACE)ez-pd-configurator  $(CY_HELP_ez-pd-configurator))

mtb_help_tools_end: mtb_help_tool_ez-pd-configurator
mtb_help_tool_ez-pd-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_ez-pd-configurator

config_lin:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name lin-configurator
.PHONY: config_lin

CY_HELP_config_lin=Launches the LIN Configurator 1.80 GUI for the target's mtblin file
CY_HELP_config_lin_VERBOSE=Launches the LIN Configurator 1.80 GUI. Check the LIN Configurator 1.80 User Guide for more information.
mtb_help_tool_config_lin:
	@:
	$(info $(MTB__SPACE)config_lin          $(CY_HELP_config_lin))

mtb_help_tools_end: mtb_help_tool_config_lin
mtb_help_tool_config_lin: mtb_help_tools_start
.PHONY: mtb_help_tool_config_lin

lin-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name lin-configurator
.PHONY: lin-configurator

CY_HELP_lin-configurator=Launches the LIN Configurator 1.80 GUI for the target's mtblin file
CY_HELP_lin-configurator_VERBOSE=Launches the LIN Configurator 1.80 GUI. Check the LIN Configurator 1.80 User Guide for more information.
mtb_help_tool_lin-configurator:
	@:
	$(info $(MTB__SPACE)lin-configurator    $(CY_HELP_lin-configurator))

mtb_help_tools_end: mtb_help_tool_lin-configurator
mtb_help_tool_lin-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_lin-configurator

.PHONY: mtb_help_tools_start mtb_help_tools_end
